"""Global rotational symmetry checks."""
from __future__ import annotations
import numpy as np

def rotation_generators() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return the standard basis of the Lie algebra so(3)."""
    return (
        np.array([[0.,0.,0.],[0.,0.,-1.],[0.,1.,0.]]),
        np.array([[0.,0.,1.],[0.,0.,0.],[-1.,0.,0.]]),
        np.array([[0.,-1.,0.],[1.,0.,0.],[0.,0.,0.]]),
    )

def infinitesimal_rotation_directions(vectors: np.ndarray) -> np.ndarray:
    """Return three flattened tangent directions generated by global rotations."""
    x = np.asarray(vectors, dtype=float)
    if x.ndim != 2 or x.shape[1] != 3:
        raise ValueError("vectors must have shape (m, 3)")
    return np.stack([(x @ generator.T).ravel() for generator in rotation_generators()])
