"""Scalar reduction for the Goldberg equivariant S^2-flow construction."""

from __future__ import annotations

from dataclasses import dataclass
from math import sqrt


@dataclass(frozen=True)
class LocalCoordinates:
    """Coordinates generated by one two-vertex Goldberg channel."""

    z: float
    delta: float
    a_x: float
    a_z: float
    b_x: float
    b_z: float


def local_coordinates(y: float, x: float) -> LocalCoordinates:
    """Evaluate the local analytic formulas for one channel parameter y."""
    z_radicand = 1.0 - y * y * (1.0 + x * x)
    delta_radicand = 3.0 - 4.0 * y * y
    if z_radicand <= 0.0:
        raise ValueError(f"Non-positive z radicand: {z_radicand}")
    if delta_radicand <= 0.0:
        raise ValueError(f"Non-positive delta radicand: {delta_radicand}")

    z = sqrt(z_radicand)
    delta = sqrt(delta_radicand)
    denominator = 2.0 * (1.0 - y * y)

    a_x = (delta * z - y * x) / denominator
    a_z = (z + delta * y * x) / denominator
    b_x = a_x + y * x
    b_z = a_z - z

    return LocalCoordinates(
        z=z,
        delta=delta,
        a_x=a_x,
        a_z=a_z,
        b_x=b_x,
        b_z=b_z,
    )


def scalar_function(s: float, x: float) -> float:
    """Return the final unit-norm equation H(s, x)."""
    t = 0.5 - s
    left = local_coordinates(s, x)
    right = local_coordinates(t, x)
    horizontal = right.b_x - left.b_x
    vertical = left.b_z - right.b_z
    return horizontal * horizontal + vertical * vertical - 0.75


def scalar_bracket() -> tuple[float, float]:
    """Return the theorem bracket for the unique scalar root."""
    return (2.0 / 3.0, 21.0 / 25.0)
